

from heatcontrol.devices.heat_calculators.heat_calculator import HeatCalculator
from heatcontrol.devices.heat_calculators.tv7_heat_calculator import TV7HeatCalculator
from heatcontrol.devices.heat_calculators.spt961m_heat_calculator import SPT961MHeatCalculator
from heatcontrol.devices.heat_calculators.carat_heat_calculator import Carat307HeatCalculator
from heatcontrol.devices.heat_calculators.sa94HeatCalculator import SA94HeatCalculator